user_name = input("Привет! Я твой фитнес-трекер. Напиши как тебя зовут!")
name_u = user_name.title()
user_age = input("Приятно познакомиться! Сколько тебе лет?")
age = int(user_age)
user_height = input("Какой у тебя рост в метрах?")
user_weight = input("Теперь напиши свой вес в килограммах!")
height = float(user_height)
weight = float(user_weight)
bmi = weight / (height ** 2)
imt = round(bmi, 1)
water_ml = weight * 30
water_l = water_ml / 1000
print(f"Отчет для пользователя: {name_u} {age} г.")
print(f"Спасибо, {name_u}! Твой индекс массы тела {imt}")
print(f"Тебе нужно выпивать {water_l} литр жидкости в день")
print(f"Расчет окончен. До свидания, {name_u}, Будьте здоровы!\n")
